# Generated by Django 4.1.7 on 2023-04-02 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_remove_cartitems_color_variant'),
        ('store', '0007_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_variant',
        ),
        migrations.DeleteModel(
            name='ColorVariant',
        ),
    ]
