# Generated by Django 4.1.7 on 2023-03-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=100)),
                ('banner_image', models.ImageField(upload_to='banner_image')),
                ('note', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
