# Generated by Django 4.1.7 on 2023-03-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_banner_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='name',
        ),
        migrations.AddField(
            model_name='carousel',
            name='carousel_name',
            field=models.CharField(default='Name', max_length=100),
        ),
    ]
