# Generated by Django 4.1.7 on 2023-04-01 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_address_phone_alter_address_pincode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_alter_banner_banner_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='profile')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
