# Generated by Django 4.1.7 on 2023-03-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_orderitem_user_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartt',
            name='cart_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
