# Generated by Django 4.1.7 on 2023-04-02 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_color_variant_delete_colorvariant'),
        ('cart', '0018_remove_cartitems_color_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='size_variant',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.varitaion'),
        ),
    ]
