# Generated by Django 4.1.7 on 2023-04-02 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_color_variant_delete_colorvariant'),
        ('cart', '0020_cartitems_size_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variantion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.varitaion'),
        ),
    ]
